core/urls.py
from django.urls import path
from .views import *

app_name = 'core'
urlpatterns = [
    path('', RegisterView.as_view(), name='register'),
    path('home/', IndexView.as_view(), name="index"),
    path('update-profile/', UpdateProfileView.as_view(), name='update_profile'),
    path('logout/', LogoutView.as_view(), name='logout')
]

dashboard/urls.py
from django.urls import path
from .views import *

app_name = 'dashboard'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('candidate/', CandidateView.as_view(), name='candidate'),
    path('candidate/<int:id>/', CandidateUpdate.as_view(), name='update'),
    path('candidate/<int:id>/delete/', CandidateDeleteView.as_view(), name='delete'),
]

polls/urls.py
from django.urls import path
from .views import *

app_name = 'polls'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'), name='core'),
    path('dashboard/', include('dashboard.urls'), name='dashboard'),
    path('polls/', include('polls.urls'), name='polls'),
    path('candidate/', include('voters.urls'), name='voters'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

voters/urls.py
from django.urls import path
from .views import *

app_name = 'voter'
urlpatterns = [
    path('', IndexView.as_view(), name="index"),
    path('vote/', VoteView.as_view(), name='vote'),
    path('update/', CandidateUpdate.as_view(), name='update')
]

templates/snippets/sidebar.html
{% load static %}

<div class="wrapper hover_collapse">
<!-- top navigation bar -->
<div class="top_navbar">

<!-- logo -->
    <div class="logo">Administrators</div>
<!-- menu button -->
   <div class="menu">
         <div class="hamburger">
         <i class="fas fa-bars"></i>
         </div>
         <div class="log">
             {% if request.user %}
             {{request.user}}
             {% endif %}
         </div>
       </div>
       </div>

<!-- side bar -->
<div class="sidebar">

  <div class="sidebar_inner">
    <!-- menu item -->
  <ul id="remove">
    <!-- <li>
    <a href="#">
  <span class="icon"><i class="fa fa-home"></i></span>
  <span class="text">Home</span>
    </a>
    </li> -->
      <li>
      <a href="{% url 'dashboard:index' %}">
    <span class="icon"><i class="fas fa-user-tie"></i></span>
    <span class="text">View Administrators</span>
      </a>
      </li>

      <li>
      <a href="{% url 'dashboard:candidate' %}">
    <span class="icon"><i class="fa fa-user"></i></span>
    <span class="text">Manage Candidate</span>
      </a>
      </li>

      <li>
      <a href="{% url 'polls:index' %}">
    <span class="icon"><i class="fas fa-poll"></i></span>
    <span class="text">Check Poll Results</span>
      </a>
      </li>
      <li>
      <a href="{% url 'core:update_profile' %}">
    <span class="icon"><i class="fas fa-user-edit"></i></span>
    <span class="text">Update Profile</span>
      </a>
      </li>
      <li>
      <a href="{% url 'core:logout' %}">
    <span class="icon"><i class="fa fa-sign-out"></i></span>
    <span class="text">Log Out</span>
      </a>
      </li>
  </ul>
</div>

</div>
</div>


<style>


.card {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  max-width: 300px;
  margin: auto;
  text-align: center;
  font-family: arial;
}

.title {
  color: grey;
  font-size: 18px;
}

button {
  border: none;
  outline: 0;
  display: inline-block;
  padding: 8px;
  color: white;
  background-color: #000;
  text-align: center;
  cursor: pointer;
  width: 100%;
  font-size: 18px;
}

a {
  text-decoration: none;
  font-size: 22px;
  color: black;
}

button:hover, a:hover {
  opacity: 0.7;
}
</style>

templates/snippets/vote_sidebar.html
{% load static %}

<div class="wrapper hover_collapse">
    <!-- top navigation bar -->
    <div class="top_navbar">

    <!-- logo -->
        <div class="logo">Candidates</div>

    <!-- menu button -->
       <div class="menu">
         <div class="hamburger">
         <i class="fas fa-bars"></i>
         </div>
         <div class="log">
             {% if request.user %}
             {{request.user}}
             {% endif %}
         </div>
       </div>
       </div>

    <!-- side bar -->
    <div class="sidebar">

      <div class="sidebar_inner">
        <!-- menu item -->
      <ul id="remove">
        <!-- <li>
        <a href="#">
      <span class="icon"><i class="fa fa-home"></i></span>
      <span class="text">Home</span>
        </a>
        </li> -->
          <li>
          <a href="{% url 'voter:index' %}">
        <span class="icon"><i class="fas fa-user-tie"></i></span>
        <span class="text">View Candidates</span>
          </a>
          </li>

          <li>
          <a href="{% url 'voter:vote' %}">
        <span class="icon"><i class="fa fa-user"></i></span>
        <span class="text">Vote Candidate</span>
          </a>
          </li>


          <!-- <li>
          <a href="#">
        <span class="icon"><i class="fa fa-key"></i></span>
        <span class="text">Update Password</span>
          </a>
          </li> -->
          <li>
          <a href="{% url 'voter:update' %}">
        <span class="icon"><i class="fas fa-user-edit"></i></span>
        <span class="text">Update Profile</span>
          </a>
          </li>
          <li>
          <a href="{% url 'core:logout' %}">
        <span class="icon"><i class="fa fa-sign-out"></i></span>
        <span class="text">Log Out</span>
          </a>
          </li>
      </ul>
    </div>

    </div>
    </div>