core/urls.py
from django.urls import path
from .views import *

app_name = 'core'
urlpatterns = [
    path('', RegisterView.as_view(), name='register'),
    path('home/', IndexView.as_view(), name="index"),
    path('update-profile/', UpdateProfileView.as_view(), name='update_profile'),
    path('logout/', LogoutView.as_view(), name='logout')
]

dashboard/urls.py
from django.urls import path
from .views import *

app_name = 'dashboard'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('candidate/', CandidateView.as_view(), name='candidate'),
    path('candidate/<int:id>/', CandidateUpdate.as_view(), name='update'),
    path('candidate/<int:id>/delete/', CandidateDeleteView.as_view(), name='delete'),
]

polls/urls.py
from django.urls import path
from .views import *

app_name = 'polls'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'), name='core'),
    path('dashboard/', include('dashboard.urls'), name='dashboard'),
    path('polls/', include('polls.urls'), name='polls'),
    path('candidate/', include('voters.urls'), name='voters'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models


class Candidate(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    position = models.CharField(max_length=255)

    def __str__(self):
        return self.first_name

dashboard/views.py
from django.contrib import messages
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from core.models import Profile
from .models import *


class IndexView(LoginRequiredMixin, View):
    login_url = 'core:register'

    def get(self, request):
        user = User.objects.filter(is_staff=True, is_superuser=False)
        context = {
            "user": user,
        }
        return render(request, "dashboard/index.html", context)


class CandidateView(LoginRequiredMixin, View):
    login_url = 'core:register'

    def get(self, request):
        candidates = Candidate.objects.all()
        context = {
            "candidates": candidates
        }
        return render(request, "dashboard/candidates.html", context)

    def post(self, request):
        first_name = request.POST.get('first_name',)
        last_name = request.POST.get('last_name',)
        position = request.POST.get('position',)

        if first_name == '' and last_name == '':
            return redirect("dashboard:candidate")

        candidate = Candidate.objects.create(first_name=first_name, last_name=last_name, position=position)
        candidate.save()

        return redirect("dashboard:candidate")


class CandidateUpdate(LoginRequiredMixin, View):
    login_url = 'core:register'

    def get(self, request, id):
        candidate = Candidate.objects.get(id=id)
        context = {
            'candidate': candidate
        }
        return render(request, "dashboard/update.html", context)

    def post(self, request, id):
        first_name = request.POST.get('first_name', )
        last_name = request.POST.get('last_name', )
        position = request.POST.get('position', )

        candidate = Candidate.objects.get(id=id)

        candidate.first_name = first_name
        candidate.last_name = last_name
        candidate.position = position
        candidate.save()
        return redirect("dashboard:candidate")


class CandidateDeleteView(LoginRequiredMixin, View):
    login_url = 'core:register'

    def get(self, request, id):
        candidate = Candidate.objects.get(id=id)
        candidate.delete()
        return redirect("dashboard:candidate")


class ProfileView(View):
    def get(self, request, slug):
        pass

templates/dashboard/candidates.html
{% load static %}
<!DOCTYPE html>
<html lang="en-US">

<head>
<meta charset="utf-8">
<meta name="viewport" content = "width = device-width, initial-scale = 1.0">
<meta http-equiv = "X-UA-Compatible" content = "ie=edge">

<!-- icon style -->
<script src ="https://kit.fontawesome.com/b99e675b6e.js"></script>
<title>Simpe header menu</title>

<!-- CSS link -->
<link rel ="stylesheet" href = "{% static 'css/style.css' %}">
    <link rel ="stylesheet" href = "{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<style>
        h1 {
            color: green;
        }
        ul#remove {
            list-style-type: none;
            padding: 0;
        }
        .left {
            width : 40%;
            float: left;
        }
        .right {
            width : 40%;
            float: right;
        }
    </style>


</head>
<body>

{% load static %}

<div class="wrapper hover_collapse">
<!-- top navigation bar -->
<div class="top_navbar">

<!-- logo -->
    <div class="logo">Candidate</div>
<!-- menu button -->
   <div class="menu">
         <div class="hamburger">
         <i class="fas fa-bars"></i>
         </div>
         <div class="log">
             {% if request.user %}
             {{request.user}}
             {% endif %}
         </div>
       </div>
       </div>

<!-- side bar -->
<div class="sidebar">

  <div class="sidebar_inner">
    <!-- menu item -->
  <ul id="remove">
    <!-- <li>
    <a href="#">
  <span class="icon"><i class="fa fa-home"></i></span>
  <span class="text">Home</span>
    </a>
    </li> -->
      <li>
      <a href="{% url 'dashboard:index' %}">
    <span class="icon"><i class="fas fa-user-tie"></i></span>
    <span class="text">View Administrators</span>
      </a>
      </li>

      <li>
      <a href="{% url 'dashboard:candidate' %}">
    <span class="icon"><i class="fa fa-user"></i></span>
    <span class="text">Manage Candidate</span>
      </a>
      </li>

      <li>
      <a href="{% url 'polls:index' %}">
    <span class="icon"><i class="fas fa-poll"></i></span>
    <span class="text">Check Poll Results</span>
      </a>
      </li>
      <li>
      <a href="{% url 'core:update_profile' %}">
    <span class="icon"><i class="fas fa-user-edit"></i></span>
    <span class="text">Update Profile</span>
      </a>
      </li>
      <li>
      <a href="{% url 'core:logout' %}">
    <span class="icon"><i class="fa fa-sign-out"></i></span>
    <span class="text">Log Out</span>
      </a>
      </li>
  </ul>
</div>

</div>
</div>


<style>


.card {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  max-width: 300px;
  margin: auto;
  text-align: center;
  font-family: arial;
}

.title {
  color: grey;
  font-size: 18px;
}

button {
  border: none;
  outline: 0;
  display: inline-block;
  padding: 8px;
  color: white;
  background-color: #000;
  text-align: center;
  cursor: pointer;
  width: 100%;
  font-size: 18px;
}

a {
  text-decoration: none;
  font-size: 22px;
  color: black;
}

button:hover, a:hover {
  opacity: 0.7;
}
</style>


<br>
<br>
<br>
<br>

<!-- Page Content -->
<table>
    <tr>
        <td>
            <form autocomplete="off" method="post">
                {% csrf_token %}

                <div>
                    <label for="productCode">First Name</label>
                    <input type="text" name="first_name" id="productCode" required>
                </div>
                <div>
                    <label for="product">Last Name</label>
                    <input type="text" name="last_name" id="product" required>
                </div>
                <div>
                    <label for="position">Position</label> <br />
                    <select id="position" name="position">
                        <option value="President">President</option>
                        <option value="Vice President">Vice President</option>
                        <option value="Secretary General">Secretary General</option>
                        <option value="Treasurer">Treasurer</option>
                    </select>
                    <!--input type="text" name="qty" id="qty"-->
                </div>

                <div class="form_action--button">
                    <input type="submit" value="Submit">
                </div>
            </form>

            <td>

                <table class="list" id="storeList">
                    <thead>
                        <tr>
                            <th>Names</th>
                            <th>Position</th>
                            <th>Edit</th>
                            <th>Delete</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for candidate in candidates %}
                            <tr>
                                <th>{{candidate.first_name}} {{candidate.last_name}}</th>
                                <th>{{candidate.position}}</th>
                                <th>
                                    <a href="{% url 'dashboard:update' candidate.id %}" style="color: green; font-size: 15px;">
                                        <i class="fas fa-pencil-alt"></i>
                                    </a>
                                </th>
                                <th>
                                    <a href="{% url 'dashboard:delete' candidate.id %}"
                                       style="color: red; font-size: 15px;" class="confirm-delete">
                                        <i class="fas fa-trash-alt"></i>
                                    </a>
                                </th>

                                <script>

                                </script>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </td>
        </td>
    </tr>
</table>

<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/manageCandidate.js' %}"></script>


<!-- Now activate menu button using Javascript -->
<script type="text/javascript">

$(document).on('click', '.confirm-delete', function(){
      return confirm('Are you sure you want to delete');
 })


var li_items = document.querySelectorAll(".sidebar ul li");
var hamburger = document.querySelector(".hamburger");
var wrapper = document.querySelector(".wrapper");

// What will change if you moove the mouse over the side bar
li_items.forEach((li_item)=>{
   li_item.addEventListener("mouseenter", ()=>{

    li_item.closest(".wrapper").classList.remove("hover_collapse");

  })
});

li_items.forEach((li_item)=>{
   li_item.addEventListener("mouseleave", ()=>{

    li_item.closest(".wrapper").classList.add("hover_collapse");

   })
});

hamburger.addEventListener("click", () => {

    hamburger.closest(".wrapper").classList.toggle("hover_collapse");
})
</script>

  </body>

</html>

templates/dashboard/index.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
<meta name="viewport" content = "width = device-width, initial-scale = 1.0">
<meta http-equiv = "X-UA-Compatible" content = "ie=edge">

<!-- icon style -->
<script src ="https://kit.fontawesome.com/b99e675b6e.js"></script>
<title>Admin Dashboard</title>

<!-- CSS link -->
<link rel ="stylesheet" href = "{% static 'css/style.css' %}">
    <link rel ="stylesheet" href = "{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<style>
        h1 {
            color: green;
        }
        ul#remove {
            list-style-type: none;
            padding: 0;
        }
        .left {
            width : 40%;
            float: left;
        }
        .right {
            width : 40%;
            float: right;
        }
    </style>


</head>


<body>

{% include 'snippets/sidebar.html' %}


  <br>
  <br>
  <br>
  <br>


<h2 style="text-align:center">Evote Admins</h2>


<div class="test">

    {% for user in user %}
        <div class="card">
            {% if user.profile.profile_image %}
                <img src="{{ user.profile.profile_image.url }}" alt="{{user.profile}}" style="width:100%">
            {% else %}
                <img src="{% static 'img/index.png' %}" />
            {% endif %}

          <h1>{{user.profile}}</h1>
          <p class="title">CEO & Co-Founder, Evote</p>
          <!--p>Harvard University</p-->
          <div style="margin: 24px 0;">
            <a href="#"><i class="fa fa-dribbble"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-linkedin"></i></a>
            <a href="#"><i class="fa fa-facebook"></i></a>
          </div>
          <p><button>Contact</button></p>
        </div>
    {% endfor %}




</div>


<!-- Now activate menu button using Javascript -->
<script type="text/javascript">
    var li_items = document.querySelectorAll(".sidebar ul li");
    var hamburger = document.querySelector(".hamburger");
    var wrapper = document.querySelector(".wrapper");

    // What will change if you moove the mouse over the side bar
    li_items.forEach((li_item)=>{
       li_item.addEventListener("mouseenter", ()=>{

        li_item.closest(".wrapper").classList.remove("hover_collapse");

      })
    });

    li_items.forEach((li_item)=>{
       li_item.addEventListener("mouseleave", ()=>{

        li_item.closest(".wrapper").classList.add("hover_collapse");

       })
    });

    hamburger.addEventListener("click", () => {

        hamburger.closest(".wrapper").classList.toggle("hover_collapse");
    })
    </script>

</body>
</html>

templates/dashboard/update.html
{% load static %}
<!DOCTYPE html>
<html lang="en-US">

<head>
<meta charset="utf-8">
<meta name="viewport" content = "width = device-width, initial-scale = 1.0">
<meta http-equiv = "X-UA-Compatible" content = "ie=edge">

<!-- icon style -->
<script src ="https://kit.fontawesome.com/b99e675b6e.js"></script>
<title>Simpe header menu</title>

<!-- CSS link -->
<link rel ="stylesheet" href = "{% static 'css/style.css' %}">
    <link rel ="stylesheet" href = "{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<style>
        h1 {
            color: green;
        }
        ul#remove {
            list-style-type: none;
            padding: 0;
        }
        .left {
            width : 40%;
            float: left;
        }
        .right {
            width : 40%;
            float: right;
        }
    </style>


</head>
<body>

{% load static %}

<div class="wrapper hover_collapse">
<!-- top navigation bar -->
<div class="top_navbar">

<!-- logo -->
    <div class="logo">Candidate</div>
<!-- menu button -->
   <div class="menu">
         <div class="hamburger">
         <i class="fas fa-bars"></i>
         </div>
         <div class="log">
             {% if request.user %}
             {{request.user}}
             {% endif %}
         </div>
       </div>
       </div>

<!-- side bar -->
<div class="sidebar">

  <div class="sidebar_inner">
    <!-- menu item -->
  <ul id="remove">
    <!-- <li>
    <a href="#">
  <span class="icon"><i class="fa fa-home"></i></span>
  <span class="text">Home</span>
    </a>
    </li> -->
      <li>
      <a href="{% url 'dashboard:index' %}">
    <span class="icon"><i class="fas fa-user-tie"></i></span>
    <span class="text">View Administrators</span>
      </a>
      </li>

      <li>
      <a href="{% url 'dashboard:candidate' %}">
    <span class="icon"><i class="fa fa-user"></i></span>
    <span class="text">Manage Candidate</span>
      </a>
      </li>

      <li>
      <a href="{% url 'polls:index' %}">
    <span class="icon"><i class="fas fa-poll"></i></span>
    <span class="text">Check Poll Results</span>
      </a>
      </li>
      <li>
      <a href="{% url 'core:update_profile' %}">
    <span class="icon"><i class="fas fa-user-edit"></i></span>
    <span class="text">Update Profile</span>
      </a>
      </li>
      <li>
      <a href="{% url 'core:logout' %}">
    <span class="icon"><i class="fa fa-sign-out"></i></span>
    <span class="text">Log Out</span>
      </a>
      </li>
  </ul>
</div>

</div>
</div>


<style>


.card {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  max-width: 300px;
  margin: auto;
  text-align: center;
  font-family: arial;
}

.title {
  color: grey;
  font-size: 18px;
}

button {
  border: none;
  outline: 0;
  display: inline-block;
  padding: 8px;
  color: white;
  background-color: #000;
  text-align: center;
  cursor: pointer;
  width: 100%;
  font-size: 18px;
}

a {
  text-decoration: none;
  font-size: 22px;
  color: black;
}

button:hover, a:hover {
  opacity: 0.7;
}
</style>


<br>
<br>
<br>
<br>

<!-- Page Content -->
<table>
    <tr>
        <td>

                <center>

            <form autocomplete="off"  method="post">
                {% csrf_token %}

                <div>
                    <label for="productCode">First Name</label>
                    <input type="text" name="first_name" id="productCode" value="{{candidate.first_name}}">
                </div> <br />
                <div>
                    <label for="product">Last Name</label>
                    <input type="text" name="last_name" id="product" value="{{candidate.last_name}}">
                </div> <br />
                <div>
                    <label for="position">Position: </label>
                    <select id="position" name="position">
                        {% if candidate.position == "President" %}
                        <option selected value="President">President</option>
                        <option value="Vice President">Vice President</option>
                        <option value="Secretary General">Secretary General</option>
                        <option value="Treasurer">Treasurer</option>
                        {% endif %}

                        {% if candidate.position == "Vice President" %}
                        <option value="President">President</option>
                        <option selected value="Vice President">Vice President</option>
                        <option value="Secretary General">Secretary General</option>
                        <option value="Treasurer">Treasurer</option>
                        {% endif %}

                        {% if candidate.position == "Secretary General" %}
                        <option value="President">President</option>
                        <option value="Vice President">Vice President</option>
                        <option selected value="Secretary General">Secretary General</option>
                        <option value="Treasurer">Treasurer</option>
                        {% endif %}

                         {% if candidate.position == "Treasurer" %}
                        <option value="President">President</option>
                        <option value="Vice President">Vice President</option>
                        <option value="Secretary General">Secretary General</option>
                        <option selected value="Treasurer">Treasurer</option>
                        {% endif %}


                    </select>
                    <!--input type="text" name="qty" id="qty"-->
                </div> <br />

                <div class="form_action--button">
                    <input type="submit" value="Update">
                </div>
            </form>
                </center>
        </td>
    </tr>
</table>

<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/manageCandidate.js' %}"></script>


<!-- Now activate menu button using Javascript -->
<script type="text/javascript">
var li_items = document.querySelectorAll(".sidebar ul li");
var hamburger = document.querySelector(".hamburger");
var wrapper = document.querySelector(".wrapper");

// What will change if you moove the mouse over the side bar
li_items.forEach((li_item)=>{
   li_item.addEventListener("mouseenter", ()=>{

    li_item.closest(".wrapper").classList.remove("hover_collapse");

  })
});

li_items.forEach((li_item)=>{
   li_item.addEventListener("mouseleave", ()=>{

    li_item.closest(".wrapper").classList.add("hover_collapse");

   })
});

hamburger.addEventListener("click", () => {

    hamburger.closest(".wrapper").classList.toggle("hover_collapse");
})
</script>

  </body>

</html>